<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Payment\Block\Transparent\Iframe $block */
$params = $block->getParams();
?>
<html>
    <head>
        <script>
        <?php if (isset($params['redirect'])): ?>
            window.location="<?= $block->escapeUrl($params['redirect']) ?>";
        <?php elseif (isset($params['redirect_parent'])): ?>
            var require = window.top.require;
            require(
                [
                    'jquery'
                ],
                function($) {
                    var parent = window.top;
                    $(parent).trigger('clearTimeout');
                    parent.location="<?= $block->escapeUrl($params['redirect_parent']) ?>";
                }
            );
        <?php elseif (isset($params['error_msg'])): ?>

            <?php
                $msg = $params['error_msg'];
                $msg = preg_replace('/^Gateway\serror:\s*/i', '', $msg);

                if($msg === "This transaction has been declined"):
                    $msg = "This transaction was declined. Please review your payment details and try again.";
                endif;
            ?>

            var require = window.top.require;
            require(
                [
                    'jquery',
                    'Magento_Ui/js/model/messageList',
                    'mage/translate',
                    'Magento_Checkout/js/model/full-screen-loader'
                ],
                function($, globalMessageList, $t, fullScreenLoader) {
                    var parent = window.top;
                    $(parent).trigger('clearTimeout');
                    fullScreenLoader.stopLoader();
                    globalMessageList.addErrorMessage({
                        message: $t('<?php echo $msg; ?>')
                    });
                }
            );
        <?php elseif (isset($params['order_success'])): ?>
            window.top.location = "<?= $block->escapeUrl($params['order_success']) ?>";
        <?php else: ?>
            var require = window.top.require;
            require(
                [
                    'jquery',
                    'Magento_Checkout/js/model/quote',
                    'Magento_Checkout/js/action/place-order',
                    'Magento_Checkout/js/action/redirect-on-success'
                ],
                function($, quote, placeOrderAction, redirectOnSuccessAction) {
                    var parent = window.top;

                    $(parent).trigger('clearTimeout');
                    $.when(
                        placeOrderAction({'method': quote.paymentMethod().method})
                    ).done(
                        function () {
                            redirectOnSuccessAction.execute();
                        }
                    );
                }
            );
        <?php endif; ?>
        </script>
    </head>
    <body></body>
</html>
