<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search search_header">
    <span class="sarch_mini_btn"><i class="fa fa-search"></i></span>
    <div class="block block-content" id="search_mini">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">             
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off" onblur="if (this.value == '') {this.value = 'Search here';}" onfocus="if (this.value == 'Search here') {this.value = '';}" value="Search here"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php //echo $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </form>
    </div>
</div>
<script>
              require([
                  'jquery',
                  "jquery/ui"
                  ], function($){
                    
                   /* $(document).on( "click", ".sarch_mini_btn",function(){
                          alert('Hi9');
                       // $(this).parent('.block-search').next('.block-content').css('display','block');
                       

                    }); */
                    $(".sarch_mini_btn" ).click(function() {
                        $("#search_mini").toggle();
                  });
                 });
</script>