<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<button type="button" id="showLeftPush" class="navbar-toggle" data-toggle="collapse">
	<i class="fa fa-bars" aria-hidden="true"></i>
	<i class="fa fa-close" aria-hidden="true"></i>
</button>
<span class="logo" >
 <a href="<?php echo $block->getUrl(''); ?>"  href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
  <img src="<?php /* @escapeNotVerified */ echo $block->getUrl('pub/media/logo/stores/1/') ?>cwlogo_1.png"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             <?php /*echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : ''*/ ?>
             <?php /*echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : ''*/ ?>
             
        />
    </a>
	</span>
<?php /* if ($block->isHomePage()):?>
    <strong class="logo">
<?php else: ?>
   
<?php endif ?>
      
<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>

<?php endif */?>

<?php $url= $block->getUrl('');
//$url=str_replace('https', 'http', $url);
 ?>

<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Organization",
  "name" : "Pump World",
  "url" : "<?php echo $url; ?>",
  "logo" : "<?php echo $url; ?>logo.png",
  "contactPoint" : [{
    "@type" : "ContactPoint",
    "telephone" : "+1-866-778-6572",
    "email" : "info@pumpworld.com",
    "contactType" : "customer service"
  }],
  "sameAs" : [
    "https://www.facebook.com/Compressor-World-LLC-128711186129/",
    "https://twitter.com/WorldAirSolutio",
    "https://www.linkedin.com/company/compressor-world-llc",
    "https://plus.google.com/+CompressorworldSuperStore/about",
    "http://www.pinterest.com/compressorworld/"
  ]
}
</script>

<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "WebSite",
  "name" : "Pump World",
  "alternateName" : "Pump World",
  "url" : "<?php echo $url; ?>"
}
</script>
