<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Review\Block\Form
 */

$login_userinfo= $block->getCurrentUser();
$email=$state=$city=$company=$country=$name=$fullname='';
if($login_userinfo){
    if($login_userinfo['customer']){
        $email=$login_userinfo['customer']->getEmail();       
        $name=$login_userinfo['customer']->getFirstName();       
        $fullname=$name.' '.$login_userinfo['customer']->getLastName();       
    }
    if($login_userinfo['address']){
        $address=$login_userinfo['address'];
        $state=$address['region_id'];
        $country=$address['country_id'];
        $city=$address['city'];
        $company=$address['company'];
    }
}

?>

<div id="product-review-container" data-role="product-review"></div>

<div class="block review-add" id="product-review-custom">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Write Your Own Review') ?></strong><a href="wrie-a-review" name="wrie-a-review"></a></div>
<div class="block-content">

<div class="custom_rating_group">
    <lable>Overall Rating</lable>
    <div class="averate_raging" id="averate_raging">
          <div class="rating-summary">
                <div title="0%" class="rating-result">
                    <span style="width:0%"><span>0</span></span>
                </div>
            </div>
    </div>    
</div>    

<?php if ($block->getAllowWriteReviewFlag()): ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <?php echo $block->getChildHtml('form_fields_before')?>
    <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
       
        <?php  if ($block->getRatings() && $block->getRatings()->getSize()): ?>
        <span id="input-message-box"></span>
        <fieldset class="field required review-field-ratings">
            <legend class="label"><span><?php /* @escapeNotVerified */ echo __('How do you rate this product?') ?><span></legend><br/>
            <div class="control">
                <div class="nested" id="product-review-table-skip">
                    <?php foreach ($block->getRatings() as $_rating): ?>
                        <div class="field choice review-field-rating">
                            <label class="label" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                            <div class="control review-control-vote">
                            <?php $options = $_rating->getOptions();?>
                            <?php $iterator = 1; foreach ($options as $_option): ?>
                                <input
                                    type="radio"
                                    name="ratings[<?php /* @escapeNotVerified */ echo $_rating->getId() ?>]"
                                    id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                    value="<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                                    class="radio"
                                    data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                    aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label" />
                            	<label
                                    class="rating-<?php /* @escapeNotVerified */ echo $iterator; ?>"
                                    for="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                    title="<?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?>"
                                    id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label">
                                    <span><?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?></span>
                                </label>
								<?php $iterator++; ?>
                            <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
            </div>
        </fieldset>
    <?php endif ?>
        <div class="field review-field-email required">
            <label for="email_field" class="label"><span><?php /* @escapeNotVerified */ echo __('E-mail') ?></span></label>
            <div class="control">
                <?php if($email) {?>
                    <label class="input-text" ><?php echo $email ?></span>
                <?php } else { ?>
                <input type="text" name="email" id="email_field" class="input-text" data-validate="{required:true, 'validate-email':true}" value="<?php echo $email ?>" />
                <?php } ?>
            </div>
        </div>
        <div class="field review-field-country">
            <label for="Company" class="label"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
            <div class="control">
                <input type="text" name="company" id="Company" class="input-text"  value="<?php echo $company ?>" />
            </div>
        </div>
        <div class="field review-field-city">
            <label for="City" class="label"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
            <div class="control">
                <input type="text" name="city" id="City" class="input-text" value="<?php echo $city ?>" />
            </div>
        </div>
        <?php
  echo $this->getLayout()
     ->createBlock("Wds\ReviewNotify\Block\CountryList")
      ->setData('state', $state)
      ->setData('country', $country)
     ->setTemplate("Wds_ReviewNotify::state.phtml")
     ->toHtml();
     ?>
        <div class="field review-field-nickname required">
            <label for="nickname_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Nickname') ?></span></label>
            <div class="control">
                <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" value="<?php echo $name ?>" />
            </div>
        </div>

        <div class="field review-field-summary required">
            <label for="summary_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Summary of Your Review') ?></span></label>
            <div class="control">
                <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}"  value="<?php echo $fullname ?>" />
            </div>
        </div>
        
        <div class="field review-field-text required">
            <label for="review_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Review') ?></span></label>
            <div class="control">
                <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
            </div>
        </div>

        <div class="field review-field-text required">
            <div class="control">
                    <input type="hidden" name="tracking" id="summary_field" class="input-text" value="<?php  echo $this->getRequest()->getParam('tracking'); ?>" />
            </div>
        </div>


    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button type="submit" class="action submit primary btn"><?php /* @escapeNotVerified */ echo __('Submit Review') ?></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": {"components":{"review-form":{"component":"Magento_Review/js/view/review"}}}    },
    "#review-form": {
        "Magento_Review/js/error-placement": {}
    }
}
</script>

 <script type="text/javascript">
require(['jquery'], function($){

    <?php if($state){ ?>
        $('#state').val('<?php echo $state ?>');

        <?php } ?>

   
    $('.review-control-vote .radio').on('change',function(){
        var total_start=0;
        var total_count=0;
        var old_rating=0;
        $('.review-control-vote .radio').each(function(){
            if($(this).prop('checked') == true){
                var start=$(this).next().attr('title'); 
                if(start==undefined){
                    if($(this).next().hasClass('mage-error')){
                       $(this).next().remove(); 
                    }
                    var start=$(this).next().attr('title');     
                }
                start=start.replace(' stars','');
                start=start.replace(' star','');
                start=eval(start);

                ratting=start*100/5;
                old_rating=old_rating+ratting;

                total_count++;

                total_start=old_rating/total_count;
                $('#averate_raging .rating-result > span').css('width',(Math.round(total_start))+'%');
            }
        }) 
    });
});    
</script>
<?php else: ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?php /* @escapeNotVerified */ echo __('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
        </div>
    </div>
<?php endif ?>
</div>
</div>