<?php
$countryList=$block->getCountries($block->getData('country'));
$regionList=$block->getRegion($block->getData('state'));  
?>

				<div class="field country" style="display:none">
                       	<label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                       	<div class="control">
                                   	<?php echo $countryList?>
                       	</div>
               </div>
 
        	 <div class="field region required">
                      	<label class="label" for="state"><span><?php /* @escapeNotVerified */ echo __('State') ?></span></label>
                      	<div class="control">
                       	<?php echo $regionList?>
                      	</div>
                      	</div>
                      	
                      	
                      	<div class="field states required" style="display:none">
                      	<label class="label" for="states"><span><?php /* @escapeNotVerified */ echo __('State') ?></span></label>
                      	<div class="control">
                       	<input name="state" id="states" title="<?php /* @escapeNotVerified */ echo __('State') ?>"  class="input-text" type="text" />
                      	</div>
                      	</div>
