<?php

/*

    MParmar: shipping option

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct();

$shipping_amount = trim($_product->getData('shipping_costs'));

if(isset($shipping_amount) && !empty($shipping_amount)):
if ($_product->isSaleable()): ?>
<?php // MG - Enable call for price start 
    $call_price = $_product->getCallForPrice();
   if($call_price!=1){ ?>
<div id="shipping-options-wrapper">
<div class="field required">
    <label class="label" for="select_4811">
        <span>Shipping option</span>
    </label>
    <div class="control">
 	<input type="radio" name="shipping-option" id="shipping-option1" value="<?php echo '$'.number_format($shipping_amount,2);?> Per Item" class="radio required"> <?php echo '$'.number_format($shipping_amount,2);?>  Shipping cost<br>
 	<input type="radio" name="shipping-option" id="shipping-option2" value="customer-carrier" class="radio required"> Ship collect with my carrier<br>
   	<input type="text" name="user_carrier_name" id="user_carrier_name" maxlength="30" placeholder="Enter your carrier name" style="display:none;" class="required">
    <div id="error-shipping-options" style="color:#ff0000;font-size:12px;display:none;font-weight:600;">This is a required field.</div>
</div>
</div>
</div>
<script type="text/javascript">
	require(['jquery','jquery/ui'], function($){ 
            
        
		// Add Text Field for Enter carrier Name
        jQuery("#user_carrier_name").hide();
		jQuery("#shipping-option2").click(function () {
		    jQuery("#user_carrier_name").show();
		});
		jQuery("#shipping-option1").click(function () {
		    jQuery("#user_carrier_name").hide();
		});

		// Required radio button validation
		jQuery('#product_addtocart_form').on('submit', function() {
			if(jQuery('input[name=shipping-option]:checked').length<=0)
			{
				jQuery("#error-shipping-options").show();
 				return false;
			}else{
				jQuery("#error-shipping-options").hide();
			}	
		});
	});
</script>   

<?php
} // MG - Enable call for price end
 endif; ?>   
<?php endif; ?>