<?php
$product_collection=$block->getFeatureProductList();
if($product_collection){
	$abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct');
	if ($product_collection->count()) : ?>

<div class="cwn_products_rt_mn_home">
<ul data-mage-init='{"slickwrapper":{
       "dots": false,
       "infinite": true,       
       "mobileFirst": true,
       "slidesToShow": 5,
       "slidesToScroll": 1,
       "responsive": [
  {
               "breakpoint": 1170,
               "settings": {
                   "slidesToScroll": 1,
                   "slidesToShow": 5
    }
           },           
  {
               "breakpoint": 1050,
               "settings": {
                   "slidesToScroll": 1,
                   "slidesToShow": 4
    }
           },
       {
               "breakpoint": 900,
               "settings": {
                   "slidesToScroll": 1,
                   "slidesToShow": 4
}
           },
           {
               "breakpoint": 767,
               "settings": {
                   "slidesToScroll": 1,
                   "slidesToShow": 3
               }
           },
           {
               "breakpoint": 479,
               "settings": {
                   "slidesToScroll": 1,
                   "slidesToShow": 2
               }
           },
           {
               "breakpoint": 319,
               "settings": {
                   "slidesToScroll": 1,
                   "slidesToShow": 1
               }
           }
       ]
   } }'>
  <?php $cnt=1;$i=0;$_columnCount=0; foreach ($product_collection as $_product_1):?>
  <li>
    <div class="thumbnail">	
    	<?php $imageurl= $block->getImageUrlByProduct($_product_1,'small_image',204,255); ?>
		<a href="<?php echo $_product_1->getProductUrl() ?>" title="<?php echo $this->stripTags($_product_1->getName(), null, true) ?>"><img data-lazy="<?php echo $imageurl ?>" width="100" height="100" alt="<?php echo $this->stripTags($_product_1->getName(), null, true) ?>" />
		</a>

</a>
    <?php $data= $block->getRatingSummary($_product_1);
        $review_count=$data->getReviewsCount();
        $rating_count=$data->getRatingSummary();
        
        if(empty($rating_count))
          $rating_count=0;

        if(empty($review_count))
          $review_count=0;

        if($review_count>1){
          $review_count_label ='Reviews';
        }else{
          $review_count_label ='Review';
        }
          
        
     ?>


<div class="ratings pro-ratings netreviews-stars">
<?php if($review_count) {?>
      <div class="product-reviews-summary">
        <div class="rating-summary">
         <div class="rating-result" title="<?php echo $rating_count ?>%">
             <span style="width:<?php echo $rating_count ?>%">
                 <span><span><?php echo $rating_count?></span>% of <span>100</span></span>
             </span>
         </div>
      </div>
      <div class="reviews-actions">
          <span><?php echo $review_count ?></span>&nbsp;<span><?php echo $review_count_label ?></span>
      </div>
    </div>
<?php } ?>
</div>		


		
    	<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setData('_product', $_product_1)->setTemplate("Magento_Catalog::product/produt_tags.phtml")->toHtml();?>
		<h4 class="product-name">
			<a href="<?php echo $_product_1->getProductUrl() ?>" title="<?php echo $this->stripTags($_product_1->getName(), null, true) ?>">
			<?php $name=  strip_tags( $_product_1->getName());
				  echo (strlen($name)>45)?substr($name,0,45)."...":$name;?>
			</a>
		</h4>
		<?php echo $abstractProductBlock->getProductPrice($_product_1) ?>
	</div>
  </li>
  <?php endforeach; ?>
</ul>
</div>
<?php 
	endif;
}
 ?>




