<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="text"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
				<input type="hidden" value="1" name="from_product" />	   
				<div class="qty-changer">
                <a href="javascript:void(0)" id="qty_inc">+</a>
                <a href="javascript:void(0)" id="qty_dec">-</a>
            </div>
        <script type="text/javascript">
		//jQuery.noConflict();
			
			
		require(['jquery','jquery/ui'], function($){ 
			jQuery(function(){
				jQuery("#qty_inc").click(function(){
					jQuery("#qty").val((+jQuery("#qty").val()+1) || 1);
				});
				jQuery("#qty_dec").click(function(){
					jQuery("#qty").val((jQuery("#qty").val()-1 > 0)?(jQuery("#qty").val() - 1) : 1);
				});
			});
		});
		
		
    </script>
            </div>
        </div>
        <?php endif; ?>
       <!-- <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php //echo $block->getChildHtml('', true) ?>
        </div> -->
    </div>
</div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<div class="model-popup1" style="display:none;">
    <div class="addto-msg">Thank you for purchase this product.</div>
    
</div>