<?php 

/*
$_masterHelper = $this->helper('Wds\Coreoverride\Helper\Master');
$current_product_id = $block->getProduct()->getId();

$prevlink = $_masterHelper->getPreviousProductUrl($current_product_id);
$nextlink = $_masterHelper->getNextProductUrl($current_product_id);


  if($prevlink) ?>
  	<a href="<?php echo $prevlink ?>" class="page-prev">Previous</a>

  <?php if($nextlink) ?>
  	<a href="<?php echo $nextlink ?>" class="page-next">Next</a>
*/
?>  	