<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

      $sku = $block->getProduct()->getSku();
?>
<div class="ratings pro-ratings netreviews-stars">
    <!-- TrustBox widget - Product Mini MultiSource (Beta) --> 
    <div class="trustpilot-widget" data-locale="en-US" data-template-id="577258fb31f02306e4e3aaf9" data-businessunit-id="5a2ef8c90a1d740ea821aecb" data-style-height="50px" data-style-width="190px" data-theme="light" data-sku="<?php echo $sku;?>"> <a href="https://www.trustpilot.com/review/compressorworld.com" target="_blank">Trustpilot</a> </div> 
    <!-- End TrustBox widget -->

</div>
<div class="pp-write_review"><a id="write-review">View Reviews</a></div>
<style type="text/css">
.star-rating.star-5 .star-1{background-color: #000 !important;}
</style>