<?php 

$_masterHelper = $this->helper('Wds\Coreoverride\Helper\Master');
$_product = $block->getProduct();
$_product_id = $_product->getId();

$grouparray = array('technical' => 'Technical Details',
                    'voltage' => 'Voltage Details',
                    'dimensional' => 'Dimensional Data',
                    'warranty'=>'Warranty'                    
                    );

$notdisplayfront = array("Manufacturer","Max Pressure","Model","Min Pressure (PSI)");

echo '<div class="techical_info_desc">';
foreach($grouparray as $key => $value){
   
    $resultcol = $_masterHelper->getTechnicalData($_product_id, $key);
    $techattribute = array();
    if($resultcol):
        $i=1;
        foreach($resultcol as $rescol){ 
            if(!in_array($rescol['attribute'], $notdisplayfront)){
                if($rescol['attributevalue']!=""){
                     $techattribute[$i]['attribute'] = $rescol['attribute'];
                    $techattribute[$i]['attributevalue'] = $rescol['attributevalue'];
                    $i++;
                }
               
            }
        }
    endif;
   
    if(count($techattribute)>0):
        echo "<h2 class='techical_info_desc_heading'>".$value."</h2>";
        echo "<table  class='techical_info_desc_table'><tbody>";
        foreach($techattribute as $tech){ 
            echo    "<tr>
                        <td>".$tech['attribute']."</td>
                        <td>".$tech['attributevalue']."</td>
                    </tr>";
        }
        echo "</tbody></table>";
    endif;
    
}

$weight = $_product->getWeight();
if($weight):
    echo "<h2 class='techical_info_desc_heading'>Weight</h2>";
    echo "<table  class='techical_info_desc_table'><tbody>";
        echo    "<tr>
                    <td>Weight (lbs)</td>
                    <td>".$weight."</td>
                </tr>";
    echo "</tbody></table>";
endif;
    
echo '</div>';

?>