<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"></label>
    <select id="sorter" data-role="sorter" class="sorter-options custom_shorting" style="display:none">
        <?php
$list_html='';
$selected_val='';
 foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php $selected_val=$block->escapeHtml(__($_order)); endif; ?> >
                <?php echo $block->escapeHtml(__($_order)); ?>
            </option>
 <?php $list_html.='<li data-value="'.$_key.'">'.$block->escapeHtml(__($_order)).'</li>'; ?>
        <?php endforeach; ?>
    </select>

 <div class="limiter-text-dropdown"><?php /* @escapeNotVerified */   echo __('Sort By').'&nbsp;' . $selected_val ?>
	<ul class="limit_dropdown">
	 <?php echo $list_html; ?>
      </ul>
    </div>

    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span></span>
        </a>
    <?php else: ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span></span>
        </a>
    <?php endif; ?>
</div>
