<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$siteurl= $this->getBaseUrl();
?>
<?php 
echo "Hello world!!";
?>
	<div class="container">
    	<div class="footer_top_mn">
        	<ul>
            	<li>
                	<i class="fa fa-truck"></i>
                    <div>
                    	<h3>Free Shipping</h3>
                        <p>Free shipping on all Rotary Screw Air Compressors.</p>
                    </div>
                </li>
                <li>
                	<i class="fa fa-usd"></i>
                    <div>
                    	<h3>Money Back Guarantee</h3>
                        <p>Our experts guarantee satisfaction 100% money back guarantee</p>
                    </div>
                </li>
                <li>
                	<i class="fa fa-life-ring"></i>
                    <div>
                    	<h3>Local Factory Support</h3>
                        <p>Local service and support on all machines, any location</p>
                    </div>
                </li>
                <li>
                	<i class="fa fa-thumbs-up"></i>
                    <div>
                        <a href="https://compressorworld.directcapital.com/" target="_blank" style="color: white">
                    	<h3>Financing Available</h3>
                        <p>0% Interest on various brands, ask for details</p>
                        </a>
                    </div>
                </li>
                <li>
                	<i class="fa fa-dashboard"></i>
                    <div>
                    	<h3>Express Delivery</h3>
                        <p>Same day shipping available for In-stock Compressors</p>
                    </div>
                </li>
            </ul>
        </div>

        <div class="footer_mid_mn">
        	<div class="footer_mid_lt">
            	<ul>
                	<li>
        			  	<h2>Customer Support <div class="ribbon">24/7</div></h2>
        				<a href="<?php echo $siteurl ?>contact">Contact Us</a>
        			    <a href="<?php echo $siteurl ?>meet-the-team">Meet the Team</a>
        				<a href="<?php echo $siteurl ?>privacy-policy">Privacy Policy</a>
        		        </li>
                        <?php /* Old Address start 
                    <li>
                    	<h2>Our Shop</h2>                        
                        <h3>Address:</h3>
                        <p>Pump World, LLC<br />32 Riverside Drive<br />Pembroke, MA 02359</p>
                        <p><a href="tel:866.778.6572">866.778.6572</a></p>
                        <p><a href="mailto:info@compressorworld.com">info@compressorworld.com</a></p>
                        <h3>Working Days/Hours:</h3>
                        <p>Mon - Fri / 8:00 AM - 5:00 PM EST</p>
                    </li>
                    /* Old Address end */  ?>

                    <li>
                        <h2>Our Shop</h2>                        
                        <h3>Address:</h3>
                        <p>Pump World, LLC<br />31 Schoosett Street, Unit 400<br />Pembroke, MA 02359</p>
                        <p><a href="tel:866.778.6572">866.778.6572</a></p>
                        <p><a href="mailto:info@pumpworld.com">info@pumpworld.com</a></p>
                        <h3>Working Days/Hours:</h3>
                        <p>Mon - Fri / 8:00 AM - 5:00 PM EST</p>
                    </li>

                    <li>
                    	<h2>Information</h2>
                        <a href="<?php echo $siteurl ?>about-us">About us</a>
                        <a href="<?php echo $siteurl ?>our-stores">Our stores</a>
            			<a href="<?php echo $siteurl ?>sitemap-category">Sitemap</a>
            			<a href="<?php echo $siteurl ?>term-condition">Terms and Conditions</a>
                    </li>
                    <li>
                    	<h2>Orders</h2>
                        <a href="<?php echo $block->getUrl('customer/account/login'); ?>">My Account</a>
                        <a href="<?php echo $siteurl ?>shipping-policy">Shipping Policy</a>
            			<a href="<?php echo $siteurl ?>returns-policy">Returns Policy</a>
            			<a href="https://compressorworld.directcapital.com/" target="_blank">Financing</a>
                        <a href="<?php echo $siteurl ?>secure-payment">Secure Payment</a>
                    </li>
                </ul>
            </div>
			<div class="footer_mid_rt">
				<?php echo $this->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe_footer.phtml')->toHtml();  ?>
				<div class="pay-box">
					<p>
                        <img src="<?php echo $block->getUrl("pub/media/payment/")?>allpayment.jpg" alt="payment"  width="343" height="72" />
					</p>
				</div>
			</div>
        </div>
    </div>	
	
	
	<div class="footer_bottom">
		<div class="container">
			<div class="footer_bottom_lt">                       
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sharkskin-footer-social-links')->toHtml(); ?>
			</div>
			<div class="footer_bottom_rt">                       
				<span class="copyright-footer"><?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Footer")->setTemplate("Magento_Theme::html/copyright.phtml")->toHtml(); ?></span>
            </div>            
        </div>
	</div>	
    
   
</div>
<?php 

$_masterHelper = $this->helper('Wds\Coreoverride\Helper\Master');
$routeName      = $_masterHelper->getRequestedRouteName();
$ControllerName      = $_masterHelper->getRequestedControllerName();

/*if($routeName!='onestepcheckout'){*/ ?>

<?php if($routeName=='onestepcheckout'){ ?>
<style>.field-error span{ color:#e80404; font-weight: 600}</style>

<?php } ?>


<span id="_GUARANTEE_SealSpan"></span>
<img style="display:none;" src="//nsg.symantec.com/Web/Seal/AltSealInfo.aspx?S=Large&T=M&Elem=ImgTagSeal&HASH=OlZTGBTVgUbG48%2FOG7jwea%2B2kgPzDY1Io90mzaEDly4sfoViTOVEA5SQQGJ3SKQlSeIWIFVrtur5%2B2pOhlWY2Q%3D%3D&CBF=AB&AB=1&DP=fn=;src=ImgTagSeal;grt=true" />
<script type="text/javascript" src="//nsg.symantec.com/Web/Seal/gjs.aspx?SN=954386289"></script>

<script type="text/javascript">
if (window._GUARANTEE && _GUARANTEE.Loaded) {
_GUARANTEE.Hash = "OlZTGBTVgUbG48%2FOG7jwea%2B2kgPzDY1Io90mzaEDly4sfoViTOVEA5SQQGJ3SKQlSeIWIFVrtur5%2B2pOhlWY2Q%3D%3D";
_GUARANTEE.WriteSeal("_GUARANTEE_SealSpan", "GuaranteedSeal");
}

</script>
<!-- begin  SnapEngage code -->

<script type="text/javascript">
require(['jquery','jquery/ui'], function($){ 
            jQuery(function(){

                $(".header_top_rt a").each(function(){
            if($(this).attr('href') == window.location.href){
                        $(this).addClass('active');
            }
        });
                               
                /**/
        /*$('#search').blur(function(){
                    $('.searchautocomplete__autocomplete').hide()
                })*/

        $(document).on('mouseleave','.searchautocomplete__autocomplete',function(){
                    $(this).hide();
                })

                $('#search').click(function(){
            if($(this).val()!=''){  
                            $('.searchautocomplete__autocomplete').show()
            }
                })
        $( "#search" ).keypress(function() {
            if($(this).val()!=''){  
                            $('.searchautocomplete__autocomplete').show()
            }else{
                $('.searchautocomplete__autocomplete').hide()
            }
        });

        $('.limiter-text-dropdown').hover(function(){
          $(this).find('.limit_dropdown').show();   
        },function(){
          $(this).find('.limit_dropdown').hide();
        })

        $('.limit_dropdown li').click(function(){
          $(this).parent().parent().parent().find('.custom_shorting').val( $(this).attr('data-value')); 
          $(this).parent().parent().parent().find('.custom_shorting').trigger('change');
        });



  var menuLeft = document.getElementById( 'push-menu' ),
                showLeftPush = document.getElementById( 'showLeftPush' ),
                body = document.body;

         

        showLeftPush.onclick = function() {
            classie.toggle( this, 'active' );
            classie.toggle( body, 'cbp-spmenu-push-toright' );
            classie.toggle( menuLeft, 'cbp-spmenu-open' );
            disableOther( 'showLeftPush' );
        };
         
        function disableOther( button ) {
            if( button !== 'showLeftPush' ) {
                classie.toggle( showLeftPush, 'disabled' );
            }
        }
        
      
      jQuery('#push-menu ul li ul li:first-child').parent().prev("a").addClass("sub_nav").after('<span class="subcat-expand"></span>');
    jQuery('#push-menu ul li ul').hide();
      jQuery('#push-menu .subcat-expand').click(function(){
        jQuery(this).toggleClass('subcat-expanded');
        jQuery(this).siblings("ul").slideToggle("slow").closest('ul').toggleClass('subcatActive');
       
      });

              
            });  


});

/*function async(u, c) {
    var d = document, t = 'script',
    o = d.createElement(t),
    s = d.getElementsByTagName(t)[0];
    o.type = 'text/javascript';
    o.async = true;
    o.defer = 'defer';

    o.src = '//' + u;
    if (c) { o.addEventListener('load', function (e) { c(null, e); }, false); }
    s.parentNode.insertBefore(o, s);
}

async('commondatastorage.googleapis.com/code.snapengage.com/js/566863df-dcda-4bae-8a1a-862776593bc3.js', function() {
});*/
</script>
<script type="text/javascript" src="https://integration.financepartners.com/ascstart.js?acv=5db2d29a-1ffd-4694-b9e9-fc49f02492c5" id="acapital"></script>
<!-- end SnapEngage code -->

<!-- Start: Bing UET Tag -->
<?php /*
<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"39000351"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script>
<!-- End: Bing UET Tag -->
*/ ?>

<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
     gtag('js', new Date());
    gtag('config', 'GTM-MW7NN48');
</script>


<!-- End Google Tag Manager -->
<?php if($ControllerName=='product'){ ?>
<script>
require(['jquery'],function($){
    
        p_id = $.trim($('.custom_product_info .product.attribute.sku .value').text());
        if($('.product-info-price .price-final_price .special-price').hasClass('special-price'))
            p_price= $.trim($('.product-info-price .price-final_price .special-price span.price').text());
        else
            p_price= $.trim($('.product-info-price .price-final_price span.price').text());
            p_price=p_price.replace('$','');
            p_price=p_price.replace(',','');



    var google_tag_params = {
        ecomm_prodid: p_id,
        ecomm_pagetype: 'product',
        ecomm_totalvalue: p_price
    }
})
</script>
<?php } ?>

 
<script type="text/javascript">
function sendGtag(p_id,p_name,p_list_name,p_brand,p_category,p_qty,p_price){
    /*alert('p_id='+p_id+','+'p_name='+p_name+','+'p_list_name='+p_list_name+','+'p_brand='+p_brand+','+'p_category='+p_category+','+'p_qty='+p_qty+','+'p_price='+p_price);*/

     gtag('event', 'add_to_cart', {
        "items": [
                    {
                        "id": p_id,
                        "name": p_name,
                        "list_name": p_list_name,
                        "brand": p_brand,
                        "category": p_category,
                        "quantity": p_qty,
                        "price": p_price
                    }
                ]
        });
}

require(['jquery'],function($){

    var cat_name= $('.breadcrumbs ul li').last().text();
    $('.catalog-category-view .action.tocart.primary.btn').click(function(){
       var parent_element=$(this).closest( "li" );
    
       p_id = $.trim($(parent_element).find('.extra-info-item').text().replace('Sku: ',''));
       p_name = $.trim($(parent_element).find('.product-item-link').text());

       <?php if($routeName=='catalog'){ ?>
            p_list_name = 'Category';
       <?php }else{ ?>
            p_list_name = 'Search Results';
       <?php }  ?>

       if($('#categoryProducts .product-items').hasClass('grid')){
            p_brand  = $.trim($(parent_element).find('.brand_img_mn img').attr('alt')); 
       }else{
            p_brand  = $.trim($(parent_element).find('.brand_logo img').attr('alt'));
       }
       
       p_category = $.trim(cat_name);
       p_qty=1;

       if($(parent_element).find('.price-final_price .special-price').hasClass('special-price'))
            p_price= $.trim($(parent_element).find('.price-final_price .special-price span.price').text());
       else
            p_price= $.trim($(parent_element).find('.price-final_price span.price').text());
            p_price=p_price.replace('$','');
            p_price=p_price.replace(',','');

       sendGtag(p_id,p_name,p_list_name,p_brand,p_category,p_qty,p_price);
    })

    $('#product_addtocart_form').submit(function(){
        var cat_name= $('.breadcrumbs ul li.item.product').prev().text();

        p_id = $.trim($('.custom_product_info .product.attribute.sku .value').text());
        p_name = $.trim($('.custom_product_info h1.page-title span').text());
        p_list_name="Product View";
        p_brand=$.trim($('.custom_product_info .product-brand-logo img').attr('alt'));
        p_category=$.trim(cat_name);
        p_qty=$.trim($('.custom_product_info .input-text.qty').val());

        if($('.product-info-price .price-final_price .special-price').hasClass('special-price'))
            p_price= $.trim($('.product-info-price .price-final_price .special-price span.price').text());
        else
            p_price= $.trim($('.product-info-price .price-final_price span.price').text());

            p_price=p_price.replace('$','');
            p_price=p_price.replace(',','');

        sendGtag(p_id,p_name,p_list_name,p_brand,p_category,p_qty,p_price);
    });
});
require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($,modal){
            var options = {
                    type: 'popup',
                    responsive: true,
                    refresh: true,
                    innerScroll: true,
                    click: function () {
                            this.clearModal();
                },
            };

             $('.request_a_quote').click(function(event){
                $('.loader').show();
                $('#popup-modal2').html('');
                event.preventDefault()
                requestQuotePopupNew($(this).attr('href'));
                var popup = modal(options, $('#popup-modal2'));
                
            });
});            

function requestQuotePopupNew(url){
    var loader=jQuery('.loader');

    jQuery.ajax({
      method: "POST",
      url: url
    }).done(function(response){
        formdata=jQuery(response).find('#container .column.main').html()
        jQuery('#popup-modal2').html(formdata);
        jQuery(loader).hide();  
        jQuery('#popup-modal2').modal('openModal');
    });
}
    function submitrequestaquote(){
        if(jQuery('#quote-form-validate #name').val()==''){
            alert('Please enter name');
        }else if(jQuery('#quote-form-validate #email').val()==''){
            alert('Please enter email');
        }else if(jQuery('#quote-form-validate #state').val()<0){
            alert('Please select state');
        }else if(jQuery('#quote-form-validate #subject').val()==''){
            alert('Please enter subject');
        }else if(jQuery('#quote-form-validate .g-recaptcha-response').val()==''){
            alert('Please veryfy captcha.');
        }else{  
            jQuery('#loader').css('display','block');
            jQuery.ajax({
              method: "POST",
              url: "<?php echo $block->getUrl('requestaquote/index/saveQuote') ?>",
              data: jQuery('#quote-form-validate').serialize()
            }).done(function( response ) {
                
                if(response=="true"){
                    jQuery("#request-success-msg").css({"color": "red", "font-size": "15px", "font-weight": "bold"});
                    jQuery("#request-success-msg").html("Captcha is not valid, Please try again.");
                    //grecaptcha.reset();
                }else{  
                    jQuery("#request-success-msg").css({"color": "green", "font-size": "15px", "font-weight": "bold"});
                    jQuery("#request-success-msg").html(response);
                    jQuery('#quote-form-validate').hide();
                }
                jQuery('#loader').css('display','none');
            //alert( "Data Saved: " + response );
             });
            return false;
        }
        return false;
    }
<?php if($routeName!='onestepcheckout'){ ?>
 require([ 'jquery','js/jquery.lazyload'],function($){ 
    $(document).ready(function(){
        $("img.lazy").lazyload();
        $("img.lazy").one("appear", function () {
            $(this).removeClass('swatch-option-loading')
        });    
    });
});
<?php } ?>
</script>
<div class="loader" style="display: none;">
            <img src="<?php echo $this->getViewFileUrl('images/loader-1.gif'); ?>" alt="Loading...">
        </div>
<div id="popup-modal2" style="display:none;">
    
</div>
<?php /*} */ ?>
<script type="text/javascript">
function popupwindow(url, title, w, h) {
  var left = (screen.width/2)-(w/2);
  var top = (screen.height/2)-(h/2);
  return window.open(url, title, 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);
}
function popupwindowvideo(url, title, w, h) {
    var left = (screen.width/2)-(w/2);
      var top = (screen.height/2)-(h/2);
      return window.open(url, title, 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);
} 
require([ 'jquery','js/jquery.lazyload'],function($){ 
    $(document).ready(function(){
        var find_techdata_class = $(".techical_info_desc").find(".technicaldatamenu").length;
        if (find_techdata_class == 0) {
            $(".pp-ic-3").hide();
            $('.tabs li[rel="tab2"]').hide();
        }
    });
});
</script>


<!-- Start of LiveChat (www.livechatinc.com) code -->
<script>
    window.__lc = window.__lc || {};
    window.__lc.license = 12599088;
    ;(function(n,t,c){function i(n){return e._h?e._h.apply(null,n):e._q.push(n)}var e={_q:[],_h:null,_v:"2.0",on:function(){i(["on",c.call(arguments)])},once:function(){i(["once",c.call(arguments)])},off:function(){i(["off",c.call(arguments)])},get:function(){if(!e._h)throw new Error("[LiveChatWidget] You can't use getters before load.");return i(["get",c.call(arguments)])},call:function(){i(["call",c.call(arguments)])},init:function(){var n=t.createElement("script");n.async=!0,n.type="text/javascript",n.src="https://cdn.livechatinc.com/tracking.js",t.head.appendChild(n)}};!n.__lc.asyncInit&&e.init(),n.LiveChatWidget=n.LiveChatWidget||e}(window,document,[].slice))
</script>
<noscript><a href="https://www.livechatinc.com/chat-with/12599088/" rel="nofollow">Chat with us</a>, powered by <a href="https://www.livechatinc.com/?welcome" rel="noopener nofollow" target="_blank">LiveChat</a></noscript>
<!-- End of LiveChat code -->

<!--<a href="#" class="footer-request" id="requestaquote_button"  onclick="popupwindow('https://www.pumpworld.com/chat.php','Chat with Us',400,530)"><p> REQUEST A QUOTE</p> <p class="subtxt">Immediate Response   </p></a>-->