<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$productId = $block->getSaleableItem()->getId();

// MG - Enable call for price start 
$call_price = $block->getSaleableItem()->getCallForPrice();
if($call_price==1){?>
    <?php $_product=$block->getSaleableItem();
$url= $block->getUrl('requestaquote/index/index').'?prodId='.$_product->getId().'&sku='.$_product->getSku(); ?>
<div class="call_for_price">
<ul>
    <li><a class="action primary btn request_a_quote" href="<?php echo $url ?>" onclick="return false" rel="nofollow" >Request a Quote</a></li>
<ul>
</div>
    <?php 
return true; 
}
// MG - Enable call for price end;

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

//echo '(( '.$priceModel->getAmount()->getValue().' ))';

?>
<?php if ($block->hasSpecialPrice()): ?>
    
    <span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __(''),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
    <?php 
    $wasp = $priceModel->getAmount()->getValue();
    $nowp = $finalPriceModel->getAmount()->getValue();
    $diff = $wasp - $nowp;
    if($diff > 0):
    ?>
    <span class="discount">
        <?php $diffprice = number_format((float)$diff, 2); ?>
        (<?php echo '-$'.$diffprice; ?>)
    </span>
    <?php endif; ?>

<span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __(''),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
<?php else: ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </span>
    <?php endif?>
<?php endif; ?>